---
name: Catalyst-Plugin-Params-Nested
version: 0.02
author: ~
abstract: Nested form parameters (ala Ruby on Rails).
license: perl
requires:
  CGI::Expand: 1.06
  Catalyst: 5.49
  Test::MockObject: 1.01
  perl: 5.8.1
provides:
  Catalyst::Plugin::Params::Nested:
    file: lib/Catalyst/Plugin/Params/Nested.pm
    version: 0.02
  Catalyst::Plugin::Params::Nested::Expander:
    file: lib/Catalyst/Plugin/Params/Nested/Expander.pm
generated_by: Module::Build version 0.2611
